# Generated by Django 3.2.3 on 2021-05-21 21:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('m_class', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('hardness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('magnetic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='viewing date')),
                ('visitor', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('L', 'Low Risk'), ('R', 'Restricted'), ('T', 'Top Secret')], default='L', max_length=1)),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mineral')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='mineral',
            name='tools',
            field=models.ManyToManyField(to='main_app.Tool'),
        ),
        migrations.AddField(
            model_name='mineral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
